### ISSUE TITLE
Enemy Formation Overlap

### ISSUE THREAD

**Issue by francium** [ericlifka/phoenix-arcade-shooter#1]
The enemies start overlapping and break formation. They also become misaligned when moving vertically (some are a pixel or two lower than others). This happens without any user interaction. 
![Screenshot](http://i.imgur.com/nYqsOxCl.png)

**Comment by ericlifka** [comment]
Thanks! I need to find a way to make their controlling scripts stay synchronized, or move them to a single controlling entity.
